services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.5.6
    environment:
      TZ: ${TZ}
      PUID: ${PUID_BAZARR}
      PGID: ${PGID_MEDIA}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:6767 || exit 1
    ports:
      - "6767:6767"
    restart: unless-stopped
    volumes:
      - ./bazarr:/config
      - ${DATA_ROOT}:/data

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.17
    environment:
      TZ: ${TZ}
      PUID: ${PUID_SONARR}
      PGID: ${PGID_MEDIA}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8989/health || exit 1
    ports:
      - "8989:8989"
    restart: unless-stopped
    volumes:
      - ./sonarr:/config
      - ${MEDIA_ROOT}:/data

  radarr:
    image: lscr.io/linuxserver/radarr:6.1.1
    environment:
      TZ: ${TZ}
      PUID: ${PUID_RADARR}
      PGID: ${PGID_MEDIA}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7878/health || exit 1
    ports:
      - "7878:7878"
    restart: unless-stopped
    volumes:
      - ./radarr:/config
      - ${MEDIA_ROOT}:/data

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0
    environment:
      TZ: ${TZ}
      PUID: ${PUID_PROWLARR}
      PGID: ${PGID_MEDIA}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9696/health || exit 1
    ports:
      - "9696:9696"
    restart: unless-stopped
    volumes:
      - ./prowlarr:/config

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4
    environment:
      TZ: ${TZ}
      PUID: ${PUID_QBITTORRENT}
      PGID: ${PGID_MEDIA}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
    ports:
      - "8080:8080" # webui
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    volumes:
      - ./qbittorrent:/config
      - ${TORRENT_ROOT}:/downloads

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.11.6
    environment:
      TZ: ${TZ}
      PUID: ${PUID_JELLYFIN}
      PGID: ${PGID_MEDIA}
    healthcheck:
      test: curl -fso /dev/null http://localhost:8096/health || exit 1 # wget not packaged
    networks:
      - default
      - www_default
    ports:
      - "8096:8096"
    restart: unless-stopped
    volumes:
      - ./jellyfin:/config
      - ${DATA_ROOT}:/data:ro

  seerr:
    image: ghcr.io/seerr-team/seerr:v3.1.0
    environment:
      TZ: ${TZ}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
    init: true
    networks:
      - default
      - www_default
    ports:
      - "5055:5055"
    restart: unless-stopped
    volumes:
      - ./seerr:/app/config

networks:
  www_default:
    external: true
