services:
  scrutiny:
    image: ghcr.io/starosdev/scrutiny:1.46.1-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8081:8080"
    volumes:
      - /run/udev:/run/udev:ro
      - ./scrutiny/config:/opt/scrutiny/config
      - ./scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
     - /dev/sda
     - /dev/sdb
     - /dev/sdc
     - /dev/sdd
    healthcheck:
      test: curl -f http://localhost:8080/api/health || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.39.0-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    ports:
      - 9000:9000
    healthcheck:
      test: wget --no-verbose --spider http://localhost:9000/api/system/status || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 3
    restart: unless-stopped
