services:
  scrutiny:
    image: ghcr.io/starosdev/scrutiny:1.50.0-omnibus
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
    healthcheck:
      test: curl -fso /dev/null http://localhost:8080/api/health || exit 1 # wget not packaged
    ports:
      - "8081:8080"
    restart: unless-stopped
    volumes:
      - /run/udev:/run/udev:ro
      - ./scrutiny/config:/opt/scrutiny/config
      - ./scrutiny/influxdb:/opt/scrutiny/influxdb

  portainer:
    image: portainer/portainer-ce:2.39.1-alpine
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9000/api/system/status || exit 1
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data

  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3
    environment:
      PUID: ${PUID_HOMEPAGE}
      PGID: ${PGID_MONITORING}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_ALLOWED_HOSTS}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

  librespeed:
    image: lscr.io/linuxserver/librespeed:6.1.0
    environment:
      TZ: ${TZ}
      PUID: ${PUID_LIBRESPEED}
      PGID: ${PGID_MONITORING}
      MODE: standalone
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/api/config || exit 1
    networks:
      - default
      - www_default
    ports:
      - "2222:80"
    restart: unless-stopped
    volumes:
      - ./librespeed:/config

networks:
  www_default:
    external: true
