services:
  swag:
    image: lscr.io/linuxserver/swag:5.4.0
    cap_add:
      - NET_ADMIN
    environment:
      TZ: ${TZ}
      PUID: ${PUID_SWAG}
      PGID: ${PGID_WWW}
      URL: ${URL}
      VALIDATION: ${VALIDATION}
      SUBDOMAINS: ${SUBDOMAINS}
      DNSPLUGIN: ${DNSPLUGIN}
      SWAG_AUTORELOAD: true
      DOCKER_MODS: linuxserver/mods:swag-dashboard
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/health || exit 1
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped
    volumes:
      - ./swag:/config

