services:
  postgres:
    image: postgres:18.3-alpine
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:33.0.3
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: ${TZ}
      PUID: ${PUID_NEXTCLOUD}
      PGID: ${PGID_DATACENTER}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost/status.php || exit 1
    networks:
      - default
      - www_default
    restart: unless-stopped
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data

  backrest:
    image: ghcr.io/garethgeorge/backrest:v1.12.1
    environment:
      TZ: ${TZ}
      BACKREST_DATA: /data
      BACKREST_CONFIG: /config/config.json
      XDG_CACHE_HOME: /cache
      TMPDIR: /tmp
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9898 || exit 1
    ports:
      - "9898:9898"
    restart: unless-stopped
    volumes:
      - ./backrest/data:/data
      - ./backrest/config:/config
      - ./backrest/cache:/cache
      - ./backrest/tmp:/tmp
      - ${BACKREST_USERDATA}:/userdata
      - ${BACKREST_REPOS}:/repos

  clamav:
    image: clamav/clamav:1.5.2_base
    restart: unless-stopped
    volumes:
      - ./clamav/config:/etc/clamav
      - ./clamav/database:/var/lib/clamav

networks:
  www_default:
    external: true
